#!/bin/bash
# Script used only in CD pipeline

set -ex

OPENBLAS_VERSION=${OPENBLAS_VERSION:-"v0.3.30"}
OPENBLAS_CHECKOUT_DIR="OpenBLAS"

# Clone OpenBLAS
git clone https://github.com/OpenMathLib/OpenBLAS.git -b "${OPENBLAS_VERSION}" --depth 1 --shallow-submodules "${OPENBLAS_CHECKOUT_DIR}"

if [[ "$BUILD_ENVIRONMENT" == *riscv64* ]]; then
    OPENBLAS_BUILD_BFLOAT16=
elif [[ "$BUILD_ENVIRONMENT" == *aarch64* ]]; then
    OPENBLAS_TARGET="ARMV8"
    OPENBLAS_BUILD_BFLOAT16=1
fi

OPENBLAS_BUILD_FLAGS="
CC=gcc${GCC_VERSION:+-${GCC_VERSION}}
NUM_THREADS=128
USE_OPENMP=1
NO_SHARED=0
DYNAMIC_ARCH=1
TARGET=${OPENBLAS_TARGET}
CFLAGS=-O3
BUILD_BFLOAT16=${OPENBLAS_BUILD_BFLOAT16}
"

make -j8 ${OPENBLAS_BUILD_FLAGS} -C $OPENBLAS_CHECKOUT_DIR
sudo make install -C $OPENBLAS_CHECKOUT_DIR

rm -rf $OPENBLAS_CHECKOUT_DIR
