name: linux-riscv64

on:
  push:
    branches:
      - manywheel-riscv64-1
    # branches:
    #   - main
    #   - release/*
    # tags:
    #   - ciflow/linux-riscv64/*
    #   - ciflow/trunk/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_type == 'branch' && github.sha }}-${{ github.event_name == 'workflow_dispatch' && github.run_id }}-${{ github.event_name == 'schedule' }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  actions: read

jobs:

  get-label-type:
    # if: github.repository_owner == 'pytorch'
    name: get-label-type
    uses: riseproject-dev/pytorch/.github/workflows/_runner-determinator.yml@manywheel-riscv64-1
    with:
      triggering_actor: ${{ github.triggering_actor }}
      issue_owner: ${{ github.event.pull_request.user.login || github.event.issue.user.login }}
      curr_branch: ${{ github.head_ref || github.ref_name }}
      curr_ref_type: ${{ github.ref_type }}

  linux-noble-riscv64-py3_12-build:
    name: linux-noble-riscv64-py3.12
    uses: ./.github/workflows/_linux-build.yml
    needs: get-label-type
    with:
      runner_prefix: ${{ needs.get-label-type.outputs.label-type }}
      build-environment: linux-noble-riscv64-py3.12
      docker-registry: rg.fr-par.scw.cloud/rise-pytorch-ci-registry
      docker-image-name: ci-image:pytorch-linux-noble-riscv64-py3.12-gcc14
      runner: linux.riscv64.2xlarge.ephemeral
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 3, runner: "${{ needs.get-label-type.outputs.label-type }}linux.riscv64.2xlarge.ephemeral" },
          { config: "default", shard: 2, num_shards: 3, runner: "${{ needs.get-label-type.outputs.label-type }}linux.riscv64.2xlarge.ephemeral" },
          { config: "default", shard: 3, num_shards: 3, runner: "${{ needs.get-label-type.outputs.label-type }}linux.riscv64.2xlarge.ephemeral" },
        ]}
    secrets: inherit

  linux-noble-riscv64-py3_12-test:
    name: linux-noble-riscv64-py3.12
    uses: ./.github/workflows/_linux-test.yml
    needs: linux-noble-riscv64-py3_12-build
    with:
      build-environment: ${{ needs.linux-noble-riscv64-py3_12-build.outputs.build-environment }}
      docker-image: ${{ needs.linux-noble-riscv64-py3_12-build.outputs.docker-image }}
      test-matrix: ${{ needs.linux-noble-riscv64-py3_12-build.outputs.test-matrix }}
    secrets: inherit
