name: riscv64

on:
  push:
    branches:
      - rise-riscv-runners
    tags:
      - ciflow/riscv64/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

permissions: read-all

jobs:
  linux-manylinux-2_39-py3-cpu-riscv64-build:
    # if: github.repository_owner == 'pytorch'
    name: linux-manylinux-2_39-py3-cpu-riscv64
    uses: ./.github/workflows/_linux-build.yml
    with:
      build-environment: linux-riscv64-binary-manywheel
      docker-image-name: rg.fr-par.scw.cloud/funcscwriseriscvrunnerappqdvknz9s/pytorch/manylinuxriscv64-builder:cpu-riscv64
      runner: ubuntu-24.04-riscv
    secrets: inherit
